name: Build Kivy Android APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip -d temp
          mkdir -p latest
          mv temp/cmdline-tools/* latest/
          rm -rf temp commandlinetools.zip

      - name: Show SDK Structure
        run: |
          echo "📁 Listing android-sdk directory"
          ls -R $HOME/android-sdk || echo "❌ SDK directory not found"
          echo "🔍 Searching for sdkmanager"
          find $HOME/android-sdk -name sdkmanager || echo "❌ sdkmanager not found"

      - name: Accept Android SDK Licenses
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip git openjdk-17-jdk python3-pip python3-setuptools python3-wheel
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Initialize buildozer
        run: buildozer init || true

      - name: Build APK
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk